cse110-fa21-group1/-cse110-fa21-group1

- admin/team.md
TeamValues.md updated properly
close #3
> Team values updated for Navya

- admin/team.md
Updated Jennifer's intro in team.md.
> added jennifer's intro to team.md

- source/spoonaular_search_api_sample/index.html
> Upated spoonacular search api sample

- source/scripts/NavBar.js
Resolved #55 - added navigation from the home page to our explore page when submitting a search through the search (navigation) bar
> Added navigation to explore

- .github/ISSUE_TEMPLATE/backend_bug.md
- .github/ISSUE_TEMPLATE/backend_feature_request.md
- .github/ISSUE_TEMPLATE/frontend_bug.md
- .github/ISSUE_TEMPLATE/frontend_feature_request.md
- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
- .gitignore
> Completed user story related issue templates

- source/Recipe.html
- source/scripts/NavBar.js
- source/scripts/Recipe.js
- source/scripts/recipeCard.js
- source/scripts/recipeDisplay.js
- source/scripts/search.js
- source/scripts/storage.js
This update...
- implemented the navigation from home.html, after searching goes to explore.html, and click on an item to navigate to the recipe.html (to display recipe details).
- implemented a Recipe class, a holder for details of a recipe, formatted for our website.
- implemented storage functions to properly store searched results and user-created recipes.
- populated the Recipe.html page using either search result or the user's own recipe.
- Resolved #68 #69 #66 #67 
TODO: Navigate from recipe manage page to recipe.html - either create a new recipe or edit recipe
> Updates for navigation, localstorage, and CRUD

- .github/ISSUE_TEMPLATE/backend_feature_request.md
> Fixed typo in backend feature request template

- source/scripts/storage.js
Included more documentation for the functions of storage.js
> Udpated comments for storage.js and edit function for recipes

- source/scripts/storage.js
Resolved #80 
Now we replace the old recipe rather than keep pushing the new one to the end of the recipes
> Updated behavior of editRecipe in storage

- source/scripts/ManageRecipe.js
- source/styles/ManageRecipe.css
- source/styles/explore.css
- source/styles/home.css
name: clean version of add customized recipe to local storage
title: Zimo-customized Recipe
body: after entering the basic info for a customized recipe and click save button in the manageRecipe.html,
the recipe is saved to local storage, user then naviage to the recipe details page of the new recipe
Checklist (defining tasks done to complete the feature or bug):
[x]: record info into recipe object (json format)
[x]: navigate to new page
> clean version of add customized recipe to local storage

- source/styles/ManageRecipe.css
- source/styles/explore.css
- source/styles/home.css
a test of how to create a pull request to main;
fixed a bug of auto pop-up hamburger menu in the Home, Explore, Create recipe pages.
> Quick Fix on Hamburger Menu

- source/Recipe.html
- source/styles/recipe.css
Text no longer overlaps when resizing window
> Resizing fixes

- source/Recipe.html
- source/styles/navbar.css
Resolved #65 
The probelm is that overflow for body was set to hidden (in navbar.css), making the page not scrollable.
> Fixed unscrollable when navBar is showing

- source/Recipe.html
- source/scripts/deleteRecipe.js
- source/scripts/storage.js
Click the delete button will remove the recipe from the storage and navigate to the home page.
> add delete button at top of recipe card

- source/ManageRecipe.html
- source/scripts/NavBar.js
- source/scripts/deleteRecipe.js
- source/scripts/recipeCard.js
- source/scripts/recipeDisplay.js
- source/scripts/search.js
- source/scripts/storage.js
- source/styles/ManageRecipe.css
I had updated the recipe structure, so it wasn't working correctly (getting the wrong attribute from class). Now it is showing the right title.
Resolved #97
> Fixed recipe title not populating correctly

- source/Explore.html
- source/Home.html
- source/ManageRecipe.html
- source/scripts/NavBar.js
Resolved #94 , now we can use navBar to navigate to different pages
TODO: hide some icons on some pages (such as hide delete on home.html)
> Added comments

- source/ManageRecipe.html
- source/scripts/ManageRecipe.js
- source/scripts/storage.js
- source/scripts/url.js
I have added a text box for inputting the URL of the website for an online recipe. Simply put on the website and click on the button next to it will populate the information from the online recipe.
Resolved #110 
Also made a minor change on separating a function (in storage.js) for formatting recipes from Spoonacular to make future implementations easier.
Resolved #112
> Implemented fetch recipes as baseline for creating recipes

- source/styles/navbar.css
> Add a bit of navbar styling

- source/Explore.html
- source/scripts/recipeCard.js
- source/scripts/storage.js
- source/styles/explore.css
- Adjusted the size of each recipe card. 
- Fixed spacing between each recipe card.
- Added a brightening effect on hover of a recipe card. 
- Added flex box property to tag wrapper. 
- Added styling to time.
- Added styling to tags.
> Fixed CSS of the entire recipe cards page.

- source/scripts/Recipe.js
- source/scripts/recipeCard.js
- source/scripts/storage.js
Added functions including pinRecipe(), unpinRecipe(), isPinned(), and pinnedRecipes() to facilitate pin functionality for later development.
Resolved #138
> Added pin support to recipe and storage 

- source/Explore.html
- source/scripts/recipeCard.js
- source/styles/explore.css
Fixed the title bug on main.
Added heart button to each card.
- Transformation animation fully implemented
- Styling should be complete and in line with figma, I might need to tune the border color of the heart just a tad because spoonacular stopped working before I could fix it.
- To see whether a card has been favorited, just check the classlist of its heart to see whether it's been liked
> Favorite buttons are done

- source/scripts/ManageRecipe.js
- source/scripts/search.js
Resolved #157 Added new api key from rapidapi
> Updated API access

- source/Explore.html
- source/Home.html
- source/Recipe.html
- source/styles/navbar.css
nav bar should be consistent on all pages not. Adjusted it to make it look like the youtube hamburger menu that Matthew showed in slack
closes #123 
closes #124
> Add changes to navbar

- source/scripts/ManageRecipe.js
- source/scripts/pin.js
- source/scripts/recipeCard.js
- source/scripts/recipeDisplay.js
- source/scripts/storage.js
- source/styles/explore.css
- source/styles/home.css
- source/styles/recipe.css
Also added back placeholder image and custom scrollbar for pages
> Added custom scrollbar for each page, fixed pinning searched recipe bug

- source/Explore.html
- source/scripts/search.js
- source/styles/explore.css
> Show message for empty search result

- source/styles/explore.css
> Fix for recipe card padding

- source/Recipe.html
- source/styles/ManageRecipe.css
- source/styles/recipe.css
> Fixed portion/serving img not showing, fixed centering issue when desc too short
